### ISSUE TITLE
Authentification error

### ISSUE THREAD

**Issue by vmiklos** [novel/goocaa#5]
Hi,

I have been a happy goocaa user for quite some time now, but all I get currently is an 'Authentification error'. Needless to say I didn't change my password recently or (AFAICT) changed anything on my side.

Is it something that changed on the server side that needs adapting goocaa? A quick feedback if it's just me (I see this on multiple machines) or it it's someone else, too would be already helpful. :-)

Thanks,

Miklos

**Comment by novel** [comment]
Hi Miklos, I also started to have this error. Need a closer look what's going on.

**Comment by novel** [comment]
So it looks like google deprecated ClientLogin: https://developers.google.com/identity/protocols/AuthForInstalledApps and OAuth should be used instead.

**Comment by vmiklos** [comment]
This new OAuth 2.0 thing looks convoluted enough to my eyes enough that I gave up implementing it in goocaa, at the end for my personal needs I just put together a quick hack that does the same as goocaa, but using their Python2 wrappers. It's here:

https://github.com/vmiklos/vmexam/tree/master/gcontacts

I'm happy to return to goocaa one day if you have time to port it to the OAuth2 mess. :-)

**Comment by vmiklos** [comment]
FWIW that was python2, the python3 version is here:

https://github.com/vmiklos/vmexam/blob/master/google/contacts/backup

**Comment by vmiklos** [comment]
Don't waste your time on this, I'm OK with my silly python script.
